<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="EDZ-20170729POB" name="com.jenkins.testforjenkins.Test01Test" tests="1" failures="1" timestamp="8 Jul 2019 06:02:39 GMT" time="2.045" errors="0">
  <testcase name="openBaiDu" time="2.045" classname="com.jenkins.testforjenkins.Test01Test">
    <failure type="java.lang.AssertionError" message="expected [融贝网官网_值得信赖的网络借贷信息中介平台] but found [百度新闻——海量中文资讯平台]">
      <![CDATA[java.lang.AssertionError: expected [融贝网官网_值得信赖的网络借贷信息中介平台] but found [百度新闻——海量中文资讯平台]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:190)
	at org.testng.Assert.assertEquals(Assert.java:200)
	at com.jenkins.testforjenkins.Test01Test.openBaiDu(Test01Test.java:32)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
]]>
    </failure>
  </testcase> <!-- openBaiDu -->
</testsuite> <!-- com.jenkins.testforjenkins.Test01Test -->
